---
- name: Check if Hyper-V is present on the machine
  win_shell: "Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V | Select-Object -expandproperty State"
  register: result
  when:
    - ansible_system is defined
    - ansible_system | lower == 'win32nt'

- name: Gather Hyper-V virtual machines
  datadope.discovery.win_hyperv_facts: {}
  when:
    - result is not skipped
    - result is not failed
    - "'Enabled' in result.stdout_lines"
