name: repo-integration
on:
  push:
  pull_request:

jobs:

  integration:
    name: Integration (${{ matrix.ansible }}+py${{ matrix.python }})
    strategy:
      matrix:
        include:
          - ansible: stable-2.12
            python: '3.10'
          - ansible: stable-2.13
            python: '3.10'
          - ansible: stable-2.14
            python: '3.10'
          - ansible: stable-2.15
            python: '3.10'
          - ansible: stable-2.16
            python: '3.10'
          - ansible: stable-2.17
            python: '3.10'
          - ansible: stable-2.18
            python: '3.11'
    runs-on: ubuntu-latest
    steps:
      # ansible-test requires the collection to be in a directory in the form
      # .../ansible_collections/NAMESPACE/COLLECTION_NAME/

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/datadope/discovery

      - name: Check out community.general
        uses: actions/checkout@main
        with:
          repository: ansible-collections/community.general
          path: ansible_collections/community/general

      - name: Set up Python ${{ matrix.python }} for Ansible ${{ matrix.ansible }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      # Install the head of the given branch (devel, stable-2.10)
      - name: Install ansible-base (${{ matrix.ansible }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      # run ansible-test integration inside of Docker.
      # The docker container has all the pinned dependencies that are required.
      # Explicitly specify the version of Python we want to test
      - name: Run integration tests
        run: ansible-test integration --color --continue-on-error --diff --controller docker:default --target controller:python=${{ matrix.python }}
        working-directory: ./ansible_collections/datadope/discovery
